#
# Builds MegaMekLab for CI using our Maven Repo each Night.
#
# Jobs:
#
#    - nightly_ci: Build MegaMekLab for CI using our Maven Repo.
#

name: MegaMekLab Nightly Maven CI

on:
  schedule:
    # Nightly at Midnight (UTC)
    # ref: https://crontab.guru/every-night
    - cron:  '0 0 * * *'

#
# Setup the Build Scan "VCS" link for all gradle invocations
#
env:
  GRADLE_OPTS: "-Dscan.link.VCS=https://github.com/MegaMek/megameklab/commit/${{ github.sha }}"

jobs:
  nightly_ci:
    # Run this job once for each combination in the
    # matrix below.
    strategy:
      matrix:
        os:   [ubuntu-latest, windows-latest]
        java: [11]

    runs-on: ${{ matrix.os }}

    name: Nightly MegaMekLab Maven CI ${{ matrix.os }} on Java ${{ matrix.java }}

    steps:

    #
    # Checkout the latest source
    # and put it in: ./megameklab
    #
    - uses: actions/checkout@v2
      with:
        path: megameklab

    #
    # Composite Build is NOT setup for this job.
    #

    #
    # Checkout the latest Megamek source
    # and put it in: ./megamek (needed for data directory)
    #
    - name: Checkout MegaMek
      uses: actions/checkout@v2
      with:
        repository: MegaMek/megamek
        path: megamek

    #
    # Setup the requested Java Version from the matrix
    #
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    # Don't run this for Windows.
    - name: Grant execute permission for gradlew (*nix or MacOS)
      working-directory: megameklab
      run: chmod +x gradlew
      if: runner.os != 'Windows'
      
    # Include --stacktrace to make some build failures easier
    # to figure out.
    - name: Build with Gradle
      working-directory: megameklab
      run: ./gradlew -I .github/build-scan-init.gradle build --stacktrace --scan

    - name: Upload Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ${{ matrix.os }}-jdk${{ matrix.java }}-maven-ci-failure-logs
        path: megameklab/build/reports/
